from selenium.webdriver.common.by import By
import time

class locators:
    patientBtn = (By.XPATH,'//*[@id="PatientTable"]/tbody/tr[1]/td[1]/div')
    # annual_Welness = (By.XPATH,'//*[@id="login-row"]/ul/li[6]/a')
    # plus_btn = (By.XPATH,'//*[@id="headingsecond"]/p/a')
    # medical_History = (By.XPATH,'//*[@id="medicalhistory"]')
    # surgical_History = (By.XPATH,'//*[@id="surgicalhistory"]')
    # family_History = (By.XPATH,'//*[@id="familyhistory"]')
    # medication_Allergies = (By.XPATH,'//*[@id="medicationallergies"]')
    # recent_Hospital_Stay = (By.XPATH,'//*[@id="recenthospital"]')
    # recent_Injuries = (By.XPATH,'//*[@id="recentinjuries"]')
    # recent_Treatments = (By.XPATH,'//*[@id="recenttreatments"]')
    #
    # medical_history_last_Q = (By.XPATH,'//*[@id="supplements"]')
    # save_btn_annual = (By.XPATH,'//*[@id="medicalhistorysavebtn"]')
    carePlanbtn = (By.XPATH, '//*[@id="login-row"]/ul/li[4]/a')
    time.sleep(4)
    start_btn = (By.ID, 'startbtn')
    # cancel_Time_btn = (By.XPATH,'//*[@id="TimerModal"]/div/div/div[2]/div/div/a[2]')
    time.sleep(2)
    # plus_careplan_btn = (By.XPATH,'//*[@id="headingTwo"]/p/a')
    # cognitive_btn1 = (By.ID, '//*[@id="notroublerecalling"]')
    # cognitive_btn1_yes = (By.XPATH, '//*[@id="yestroublerecalling"]')
    time.sleep(2)
    # cognitive_input_yes = (By.XPATH,'//*[@id="troublerecalling"]')
    cognitive_btn2 = (By.XPATH, '//*[@id="norecentconversations"]')
    cognitive_btn3 = (By.XPATH, '//*[@id="nodifficultyfinding"]')
    cognitive_btn4 = (By.XPATH, '//*[@id="notroublemanaging"]')
    cognitive_btn5 = (By.XPATH, '//*[@id="nodementia"]')
    cognitive_save_btn = (By.XPATH, '//*[@id="cognitiveevaluationsavebtn"]')
    # psychosocial_plus_btn = (By.XPATH, '//*[@id="headingThree"]/p/a')
    # psychosocial_btn1 = (By.XPATH, '//*[@id="nolackfriends"]')
    # psychosocial_btn2 = (By.XPATH, '//*[@id="nostayingasleep"]')
    # psychosocial_btn3 = (By.XPATH, '//*[@id="noalcohol"]')
    # psychosocial_btn4 = (By.XPATH, '//*[@id="noanxietydisorder"]')
    # psychosocial_btn5 = (By.XPATH, '//*[@id="nocompulsivedisorder"]')
    # psychosocial_btn6 = (By.XPATH, '//*[@id="nobipolardisorder"]')
    # psychosocial_btn7 = (By.XPATH, '//*[@id="noCheck12"]')
    # psychosocial_btn8 = (By.XPATH, '//*[@id="nodepression"]')
    # psychosocial_btn9 = (By.XPATH, '//*[@id="noabusedisorder"]')
    # psychosocial_btn10 = (By.XPATH, '//*[@id="noSchizoaffective"]')
    # psychosocial_btn11 = (By.XPATH, '//*[@id="notallradio"]')
    # psychosocial_btn12 = (By.XPATH, '//*[@id="notatallradio"]')
    # psychosocial_save_btn13 = (By.XPATH, '//*[@id="PsyAnalysissavebtn"]')
