class signup_testData:
    base_url = 'https://hmsccm.azurewebsites.net/'
    practicename = 'Test Practice'
    practiceaddress1 = 'abc'
    practiceaddress2 = 'xyz'
    Country = 'US'
    city = 'Miami'
    filter = 'Florida'
    doc_designation = 'MD'
    providerfirstname = 'Michael'
    providerlastname = 'Doc'
    username = 'mike'
    email = 'mike@gmail.com'
    AlertEmail = 'mike1@gmail.com'
    contactno = '(212)-363-0114'
    Pass = 'Keyboard@123'
    Cpass = 'Keyboard@123'
    zip = '12345'
